// apps/angular/src/app/pages/reviews-page/reviews-page-header/reviews-header.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IDoctor } from '../../../data-types/doctor-types';
import { MatButtonModule } from '@angular/material/button';
import { AppButtonComponent } from '../../../shared/button/button.component';

@Component({
  selector: 'app-reviews-header',
  standalone: true,
  imports: [CommonModule, MatButtonModule, AppButtonComponent],
  templateUrl: './reviews-header.component.html',
  styleUrls: ['./reviews-header.component.scss'],
})
export class ReviewsHeaderComponent implements OnInit {
  constructor() {}

  fullName: string = '';

  @Input() doctor: IDoctor = {
    id: '',
    rating: 0,
    reviewsCount: 0,
    userId: '',
    payrate: 0,
    about: '',
    firstName: '',
    lastName: '',
    avatarKey: '',
    email: '',
    phone: '',
    specializations: [],
    hospitals: [],
  };

  @Input() openSchedule: () => void = () => {};

  ngOnInit(): void {
    this.fullName = `${this.doctor.firstName} ${this.doctor.lastName}`;
  }
}

<div class="reviews-header">
  <img width="112" height="112" [src]="doctor.avatarKey" [alt]="fullName" class="avatar" />

  <div class="details">
    <div class="header">
      <span class="name">{{ fullName }}</span>
      <app-button>Book appointment</app-button>
    </div>

    <div>
      <span class="specialization">{{ doctor.specializations[0].name }}</span>

      <div class="rating">
        <div class="stars">
          <i
            class="fa-solid fa-star"
            *ngFor="let i of [].constructor(5); let idx = index"
            [ngClass]="{
              'star-size text-main-dark': doctor.rating > idx,
              'star-size text-grey-5': doctor.rating <= idx
            }"
            style="margin-right: 4px">
          </i>
        </div>

        <span class="reviews-count">
          Total reviews:
          <span>{{ doctor.reviewsCount }}</span>
        </span>
      </div>
    </div>
  </div>
</div>

// apps/frontend/src/pages/Reviews/ReviewsHeader.tsx
import { Button, Icon } from '@/components/UI';
import { IDoctor } from '@/dataTypes/Doctor';

type ReviewsHeader = {
  doctor: IDoctor;
  openSchedule: () => void;
};

export default function ReviewsHeader({ doctor, openSchedule }: ReviewsHeader) {
  const { avatarKey, firstName, lastName, specializations } = doctor;
  const fullName = `Dr. ${firstName} ${lastName}`;

  return (
    <div className='flex w-3/5 items-center gap-x-6'>
      <img width={112} height={112} src={avatarKey} alt={fullName} className='rounded-lg' />

      <div className='flex flex-1 flex-col gap-y-2'>
        <div className='flex justify-between'>
          <span className='text-2xl font-bold text-black'>{fullName}</span>
          <Button onClick={openSchedule} type='primary' btnType='button'>
            Book appointment
          </Button>
        </div>

        <div className='flex flex-col gap-y-2'>
          <span className='text-base font-medium text-grey-1'>{specializations[0].name}</span>

          <div className='flex items-center gap-x-3'>
            <div className='flex cursor-default gap-x-1'>
              {Array.from({ length: 5 }, (_, i) => (
                <Icon
                  key={'star-' + i}
                  variant='star'
                  className={`h-[18px] w-[18px] ${doctor.rating > i ? 'text-main-dark' : 'text-grey-5'}`}
                />
              ))}
            </div>

            <span className='cursor-default text-text'>
              Total reviews: <span className='font-bold text-black'>{doctor.reviewsCount}</span>
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
